In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import rich
import json
import polars as pl
import uuid
import sqlalchemy

import app.models as models
from app.config import Config
from app.database import init_db

In [3]:
with open("data/persons.json") as f:
    persons = json.load(f)["items"]

In [4]:
config = Config.from_file("config.toml")

In [5]:
rich.print(config)

Config(
    logging=LoggingConfig(level='INFO', format_str='%(asctime)s - %(name)s - %(levelname)s - %(message)s'),
    postgres=PostgresConfig(
        host='localhost',
        port=5432,
        user='pure_db_user',
        password='password',
        database_name='pure_db',
        sqlalchemy_database_uri=PostgresDsn('postgresql+psycopg2://pure_db_user:password@localhost:5432/pure_db')
    )
)

In [6]:
engine = init_db(config)

In [7]:
import app.load.pure.persons

In [8]:
df = app.load.pure.persons.transform_persons(persons).collect()

In [9]:
app.load.pure.persons.load_persons(df, engine.connect())

In [10]:
df.head(1)

shape: (1, 3)
┌─────────────────────────────────┬───────────────────────────────┬────────────────────────────────┐
│ person_id                       ┆ name                          ┆ raw                            │
│ ---                             ┆ ---                           ┆ ---                            │
│ str                             ┆ str                           ┆ struct[27]                     │
╞═════════════════════════════════╪═══════════════════════════════╪════════════════════════════════╡
│ 2b5c936a-4af4-44f9-9cc3-4e47a2… ┆ Евгений Александрович Поляков ┆ {143835,"50063896","synchronis │
│                                 ┆                               ┆ …                              │
└─────────────────────────────────┴───────────────────────────────┴────────────────────────────────┘

In [11]:
#df = pl.read_database("SELECT uuid::text, name FROM public.persons LIMIT 4", engine.connect())
df = pl.read_database(sqlalchemy.select(sqlalchemy.cast(models.Person.id, sqlalchemy.String), models.Person.name).limit(8), engine.connect())

In [12]:
df

shape: (8, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ person_id                       ┆ name                            │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ 2b5c936a-4af4-44f9-9cc3-4e47a2… ┆ Евгений Александрович Поляков   │
│ 382d6400-1743-4b2e-9865-06111d… ┆ Нина Викторовна Христофорова    │
│ 0044a9fd-df70-4404-b9ff-3258cb… ┆ Андрей Александрович Бояркин    │
│ f6930ab5-8051-4efb-8890-d82647… ┆ Александр Вячеславович Курочки… │
│ 3aa5a1ae-00b9-4222-b856-4bc21c… ┆ Лариса Дмитриевна Скоморохина   │
│ cd4009ba-4c4d-470f-a8bb-906050… ┆ Татьяна Николаевна Иванова      │
│ 93a5102c-ac3e-4025-8dde-373b91… ┆ Михаил Викторович Архипов       │
│ ede7900d-47e1-4303-9a26-a03713… ┆ Гита Георгиевна Паскерова       │
└─────────────────────────────────┴─────────────────────────────────┘

In [13]:
df.filter(pl.col("person_id") == "2b5c936a-4af4-44f9-9cc3-4e47a2cf4ba2")

shape: (1, 2)
┌─────────────────────────────────┬───────────────────────────────┐
│ person_id                       ┆ name                          │
│ ---                             ┆ ---                           │
│ str                             ┆ str                           │
╞═════════════════════════════════╪═══════════════════════════════╡
│ 2b5c936a-4af4-44f9-9cc3-4e47a2… ┆ Евгений Александрович Поляков │
└─────────────────────────────────┴───────────────────────────────┘