# ETL notebook

Здесь показаны некоторые возможности сервиса

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import json

import polars as pl
import rich

from app.config import Config
from app.database import init_db

## Загрузим json данные
(можно сказать extract шаг)

In [3]:
with open("data/persons.json") as f:
    persons = json.load(f)["items"]
with open("data/organisational-units.json") as f:
    organisational_units = json.load(f)["items"]
with open("data/classification-schemes.json") as f:
    classification_schemes = json.load(f)["items"]
with open("data/research-outputs.json") as f:
    research_outputs = json.load(f)["items"]

Размер всех данных в pure:

In [4]:
size_persons = 9.25 / 1000 * 120000
size_units = 2.78 / 1000 * 10000
size_outputs = 15.35 / 1000 * 250000
print(size_persons / 1024)
print(size_units / 1024)
print(size_outputs / 1024)

1.083984375
0.0271484375
3.7475585937499996

## Прочитаем и выведем конфиг, инициализируем состояние

In [5]:
config = Config.from_file("config.toml")

In [6]:
rich.print(config)

Config(
    logging=LoggingConfig(level='DEBUG', format_str='%(asctime)s - %(name)s - %(levelname)s - %(message)s'),
    postgres=PostgresConfig(
        host='localhost',
        port=5432,
        user='pure_db_user',
        password='password',
        database_name='pure_db',
        sqlalchemy_database_uri=PostgresDsn('postgresql+psycopg2://pure_db_user:password@localhost:5432/pure_db')
    )
)

In [7]:
engine = init_db(config)

## Transform + Load

In [8]:
import app.load.pure.classification_schemes
import app.load.pure.organisational_units
import app.load.pure.persons
import app.load.pure.research_outputs

### organisational_units

In [9]:
organisational_units_df = app.load.pure.organisational_units.transform(organisational_units).collect()

In [10]:
organisational_units_df.head(2)

shape: (2, 8)
┌─────────────┬─────────┬─────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ organisatio ┆ pure_id ┆ type_id ┆ name_en    ┆ name_ru    ┆ parents    ┆ ids        ┆ raw        │
│ nal_unit_id ┆ ---     ┆ ---     ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ ---         ┆ i64     ┆ i64     ┆ str        ┆ str        ┆ list[str]  ┆ list[struc ┆ str        │
│ str         ┆         ┆         ┆            ┆            ┆            ┆ t[6]]      ┆            │
╞═════════════╪═════════╪═════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ abf8fae5-47 ┆ 19926   ┆ 17276   ┆ Federal    ┆ Федерально ┆ null       ┆ [{28145406 ┆ {"pureId": │
│ 8f-4b63-8a8 ┆         ┆         ┆ State      ┆ е государс ┆            ┆ ,28135348, ┆ 19926,"ext │
│ c-944750…   ┆         ┆         ┆ Budgetary  ┆ твенное    ┆            ┆ "60031888" ┆ ernalId":" │
│             ┆         ┆         ┆ Educat…    ┆ бю…        ┆            ┆ …          ┆ …          │
│ 48d3663f-c0 ┆ 19939   ┆ 17278   ┆ Doctoral   ┆ аспирантур ┆ ["abf8fae5 ┆ null       ┆ {"pureId": │
│ 69-4000-bb5 ┆         ┆         ┆ (aspirantu ┆ а          ┆ -478f-4b63 ┆            ┆ 19939,"ext │
│ 3-efeec4…   ┆         ┆         ┆ ra)        ┆            ┆ -8a8c-9447 ┆            ┆ ernalId":" │
│             ┆         ┆         ┆ program…   ┆            ┆ …          ┆            ┆ …          │
└─────────────┴─────────┴─────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

## persons

In [11]:
persons_df = app.load.pure.persons.transform(persons).collect()

In [12]:
persons_df.head(1)

shape: (1, 10)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ person_id  ┆ pure_id ┆ first_nam ┆ last_name ┆ … ┆ titles    ┆ staff_uni ┆ student_u ┆ raw       │
│ ---        ┆ ---     ┆ e         ┆ ---       ┆   ┆ ---       ┆ t         ┆ nit       ┆ ---       │
│ str        ┆ i64     ┆ ---       ┆ str       ┆   ┆ list[stru ┆ ---       ┆ ---       ┆ str       │
│            ┆         ┆ str       ┆           ┆   ┆ ct[4]]    ┆ list[stru ┆ list[stru ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆ ct[2]]    ┆ ct[2]]    ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2b5c936a-4 ┆ 143835  ┆ Евгений   ┆ Поляков   ┆ … ┆ null      ┆ [{"3c70bc ┆ null      ┆ {"pureId" │
│ af4-44f9-9 ┆         ┆ Александр ┆           ┆   ┆           ┆ 8d-1758-4 ┆           ┆ :143835," │
│ cc3-4e47a2 ┆         ┆ ович      ┆           ┆   ┆           ┆ 1dd-b716- ┆           ┆ externalI │
│ …          ┆         ┆           ┆           ┆   ┆           ┆ 5c2…      ┆           ┆ d":…      │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## research_outputs

In [13]:
research_outputs_df = app.load.pure.research_outputs.transform(research_outputs).collect()

In [14]:
research_outputs_df.head(2)

shape: (2, 10)
┌────────────┬─────────┬─────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ research_o ┆ pure_id ┆ type_id ┆ category_t ┆ … ┆ external_p ┆ organisat ┆ title     ┆ raw       │
│ utput_id   ┆ ---     ┆ ---     ┆ ype_id     ┆   ┆ erson_asso ┆ ional_uni ┆ ---       ┆ ---       │
│ ---        ┆ i64     ┆ i64     ┆ ---        ┆   ┆ ciations   ┆ t_associa ┆ str       ┆ str       │
│ str        ┆         ┆         ┆ i64        ┆   ┆ ---        ┆ tio…      ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ list[struc ┆ ---       ┆           ┆           │
│            ┆         ┆         ┆            ┆   ┆ t[3]]      ┆ list[str] ┆           ┆           │
╞════════════╪═════════╪═════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ad1188e7-9 ┆ 3732230 ┆ 3985    ┆ 3937       ┆ … ┆ []         ┆ ["1e4b782 ┆ Новая     ┆ {"pureId" │
│ b4c-409f-8 ┆         ┆         ┆            ┆   ┆            ┆ 9-b1ed-40 ┆ форма при ┆ :3732230, │
│ 717-9be5eb ┆         ┆         ┆            ┆   ┆            ┆ be-b417-3 ┆ граничног ┆ "external │
│ …          ┆         ┆         ┆            ┆   ┆            ┆ 03f…      ┆ о сотр…   ┆ Id"…      │
│ cffb05ce-c ┆ 3733830 ┆ 3985    ┆ 3937       ┆ … ┆ []         ┆ ["5d626af ┆ Рецензия  ┆ {"pureId" │
│ 824-4588-8 ┆         ┆         ┆            ┆   ┆            ┆ a-9023-45 ┆ на моногр ┆ :3733830, │
│ 5f7-986605 ┆         ┆         ┆            ┆   ┆            ┆ de-b4e4-9 ┆ афию      ┆ "external │
│ …          ┆         ┆         ┆            ┆   ┆            ┆ 4b5…      ┆ А.В.Смо…  ┆ Id"…      │
└────────────┴─────────┴─────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

## classification_schemes

In [15]:
classification_schemes_df = app.load.pure.classification_schemes.transform(classification_schemes).collect()

In [16]:
classification_schemes_df.head(2)

shape: (2, 7)
┌──────────────┬─────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ classificati ┆ pure_id ┆ base_uri     ┆ description_ ┆ description_ ┆ classificati ┆ raw         │
│ on_scheme_id ┆ ---     ┆ ---          ┆ en           ┆ ru           ┆ ons          ┆ ---         │
│ ---          ┆ i64     ┆ str          ┆ ---          ┆ ---          ┆ ---          ┆ str         │
│ str          ┆         ┆              ┆ str          ┆ str          ┆ list[struct[ ┆             │
│              ┆         ┆              ┆              ┆              ┆ 5]]          ┆             │
╞══════════════╪═════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 0375dc3c-a4e ┆ 103     ┆ /dk/atira/pu ┆ Types for    ┆ Типы схем    ┆ [{105,"/dk/a ┆ {"pureId":1 │
│ 9-4ed4-8f88- ┆         ┆ re/core/clas ┆ classificati ┆ классификаци ┆ tira/pure/co ┆ 03,"uuid":" │
│ 379359…      ┆         ┆ sifica…      ┆ on schem…    ┆ и...         ┆ re/cla…      ┆ 0375dc3c…   │
│ 7c7b849b-ac5 ┆ 118     ┆ /dk/atira/pu ┆ Organisation ┆ Organisation ┆ [{120,"/dk/a ┆ {"pureId":1 │
│ 3-47fb-bcbb- ┆         ┆ re/organisat ┆ name         ┆ name         ┆ tira/pure/or ┆ 18,"uuid":" │
│ d0a3fb…      ┆         ┆ ion/na…      ┆ variants     ┆ variants     ┆ ganisa…      ┆ 7c7b849b…   │
└──────────────┴─────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

## Some select examples

In [17]:
import app.queries

In [18]:
with engine.connect() as conn:
    df = pl.read_database(
        app.queries.select_units_with_all_children(),
        conn,
    )
df

shape: (962, 3)
┌─────────────────────────────────┬─────────────────────────────────┬─────────────────┐
│ organisational_unit_id          ┆ highest_parent_organisational_… ┆ recursion_level │
│ ---                             ┆ ---                             ┆ ---             │
│ object                          ┆ object                          ┆ i64             │
╞═════════════════════════════════╪═════════════════════════════════╪═════════════════╡
│ 0435d70c-2eef-4944-90ed-649c91… ┆ 0435d70c-2eef-4944-90ed-649c91… ┆ 1               │
│ 076ea2c3-3f32-418e-b15d-1e7d45… ┆ 076ea2c3-3f32-418e-b15d-1e7d45… ┆ 1               │
│ 1249292b-434e-4ea8-9d38-879f8a… ┆ 1249292b-434e-4ea8-9d38-879f8a… ┆ 1               │
│ 22605ec4-54b3-4c1b-8410-00b6d0… ┆ 22605ec4-54b3-4c1b-8410-00b6d0… ┆ 1               │
│ 2276ef9b-8822-4559-9230-7cb7f2… ┆ 2276ef9b-8822-4559-9230-7cb7f2… ┆ 1               │
│ …                               ┆ …                               ┆ …               │
│ a078d023-e49d-46a1-816d-e94561… ┆ fa16f0e6-7f91-4599-b935-e86e16… ┆ 3               │
│ b3801895-abdb-4f66-abb0-5f682e… ┆ fa16f0e6-7f91-4599-b935-e86e16… ┆ 3               │
│ cecb9f08-be71-4a8a-a1c4-f6ae25… ┆ fa16f0e6-7f91-4599-b935-e86e16… ┆ 3               │
│ e15ae041-a274-4396-9e71-7cb6a3… ┆ fa16f0e6-7f91-4599-b935-e86e16… ┆ 3               │
│ fb99a210-b4a4-4f0f-9b40-2797b8… ┆ fa16f0e6-7f91-4599-b935-e86e16… ┆ 3               │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────┘