# Исследование Classification Schemes

У `research-output` в схеме есть поле `category` и `type`.
Оба определяются как тип `WSClassification`.
Используя инструменты, полученные при анализе `research-outputs.json`, проведем похожий анализ и для `classification-schemes.json`.

## Импорт зависимостей

In [1]:
# imports
import os
import json
import pandas as pd

In [2]:
from notebooks import utils

## Чтение выборки

In [3]:
classification_data = utils.load_from_json('../data/classification-schemes.json')['items']

## Чтение спецификации

In [4]:
SWAGGER_SPEC_URL = 'https://pure.spbu.ru/ws/api/522/swagger.json'
api_spec = utils.fetch_api_swagger_json(SWAGGER_SPEC_URL)

Fetched successfully!

In [5]:
api_spec['definitions']['WSClassification']['properties']

{'pureId': {'type': 'integer', 'format': 'int64', 'xml': {'attribute': True}},
 'externalId': {'type': 'string', 'xml': {'attribute': True}},
 'externalIdSource': {'type': 'string', 'xml': {'attribute': True}},
 'externallyManaged': {'type': 'boolean', 'xml': {'attribute': True}},
 'uri': {'type': 'string', 'xml': {'attribute': True}},
 'term': {'$ref': '#/definitions/WSLocalizedString'},
 'disabled': {'type': 'boolean', 'xml': {'attribute': True}},
 'description': {'$ref': '#/definitions/WSLocalizedString'},
 'classificationRelations': {'type': 'array',
  'xml': {'wrapped': True},
  'items': {'xml': {'name': 'classificationRelation'},
   '$ref': '#/definitions/WSClassificationRelation'}}}

Чтобы не вызывать все методы в деталях, напишем функцию, которая соберет все util-методы для аналитики в одном месте.

In [6]:
def generate_frequences_report(spec, schema_name, items):
    schema_df = utils.fetch_schema(spec, schema_name)
    
    known_frequences, unknown_frequences = utils.count_field_frequences(
        items = items, 
        keys = list(schema_df['field'])
    )

    known_frequences_df = pd.DataFrame(known_frequences.items(), columns=['field', 'count'])
    unknown_frequences_df = pd.DataFrame(unknown_frequences.items(), columns=['field', 'count'])

    schema_fields_freqs = pd.merge(
        left=schema_df, 
        right=known_frequences_df, 
        on='field', 
        how='outer'
    ).sort_values(
        by='count',
        ascending=False
    )

    return schema_fields_freqs, unknown_frequences_df

In [7]:
schema_fields_freqs, unknown_fields_freqs = generate_frequences_report(
    api_spec,
    'WSClassification',
    classification_data
)

In [8]:
unknown_fields_freqs

                      field  count
0                      uuid    315
1                   baseUri    315
2                      info    315
3        typeClassification    264
4  containedClassifications    281
5         associatedSchemes      1

## Парсинг атрибутов в выборке

Попробуем уложить классификации в pandas dataframe, чтобы уловить зависимости.
Будем искать `uri`, `uuid`, `description`, `containedClassifications`.

Из `containedClassifications` попробуем также вытащить `uri`, чтобы понять семантику.

In [ ]:
def parse_classifications(classification_data):
    result =[]

    for classification in classification_data:
        parsed_object = dict()
        parsed_object['pure_id'] = classification['pureId']
        parsed_object['uuid'] = classification['uuid']

        # get base uri for root entry
        base_uri = classification['baseUri']
        parsed_object['uri'] = base_uri

        # find description
        if 'description' in classification.keys():
            localized_descriptions = classification['description']['text']
            parsed_object['description'] = localized_descriptions[0]['value']
        else:
            parsed_object['description'] = 'None'

        if 'containedClassifications' in classification.keys():
            contained_classifications = classification['containedClassifications']
            contained_classifications_ids = dict()

            for contained_classification in contained_classifications:
                cc_pure_id = contained_classification['pureId']
                cc_uri = contained_classification['uri'].replace(base_uri, '')
                contained_classifications_ids[cc_pure_id] = cc_uri
            
            parsed_object['contained_classifications_ids'] = contained_classifications_ids
        else:
            parsed_object['contained_classifications_ids'] = {}
        
        result.append(parsed_object)
    
    return result

In [10]:
parsed_classification = parse_classifications(classification_data)
parsed_classification_df = pd.DataFrame(parsed_classification)
parsed_classification_df.sort_values(by='pure_id').head()

,pure_id,uuid,uri,description,contained_classifications_ids
0,103,0375dc3c-a4e9-4ed4-8f88-3793594e4543,/dk/atira/pure/core/classificationschemes,Types for classification schemes,"{105: '/taxonomi', 107: '/misc', 109: '/role',..."
1,118,7c7b849b-ac53-47fb-bcbb-d0a3fb58abfe,/dk/atira/pure/organisation/namevariants,Organisation name variants,"{120: '/shortname', 122: '/sortname', 124: '/w..."
2,129,989ffa0b-ace5-42d8-a9f5-30e2f559af7f,/dk/atira/pure/organisation/organisationaddres...,Address types,{17328: '/visiting_address'}
3,135,9f7b3f0c-dd07-4484-b821-a56f4513b84d,/dk/atira/pure/organisation/organisationphonen...,Phone number types,"{137: '/phone', 139: '/fax', 141: '/mobile', 1..."
4,145,742de1ad-ab79-4dc9-95ac-20898a14442a,/dk/atira/pure/organisation/organisationwebadd...,Web address types,{17322: '/official_website'}

Можно попробовать поискать записи, которые хоть немного связаны с научной деятельностью

In [11]:
parsed_classification_df[parsed_classification_df['uri'].str.contains('research', case = False)]

,pure_id,uuid,uri,description,contained_classifications_ids
30,919,6b8367bf-8b1f-44cf-9b39-6e619c1599a8,/dk/atira/pure/links/researchoutput,Types of links for Research output,"{921: '/unspecified', 12683: '/scopuspublicati..."
35,947,7befd009-b675-4947-a2ca-f857a8eb3006,/dk/atira/pure/researchoutput/status,Publication state,"{949: '/inprep', 951: '/submitted', 953: '/inp..."
64,2106,5e61f0db-1a5c-43ac-a19d-aa2f8db57997,/dk/atira/pure/association/bidirectional/resea...,Research output associations,"{4258: '/predecessor', 4261: '/successor'}"
68,2696,d6514cb5-0b5f-40f6-87fb-6fd4ed8fd309,/dk/atira/pure/researchoutput/openaccesspermis...,Types of open access states for publications,"{2698: '/open', 2700: '/embargoed', 2702: '/cl..."
85,2816,ab877d40-99dc-4cc8-b3d6-086bc2373f53,/dk/atira/pure/researchoutputref2014/researcho...,Research Output REF2014 types,"{2818: '/researchoutputref2014', 2821: '/resea..."
86,2825,aa4a3e1a-c2d2-4d8c-b839-00f6a3b4df4f,/dk/atira/pure/researchoutput/researchoutputtypes,Types of research output,"{2827: '/contributiontobookanthology', 3949: '..."
89,2870,9ba6a38c-301e-4dd8-9a9b-45405d5149e4,/dk/atira/pure/equipment/research_technique,Equipment research technique,{16844: '/other'}
100,2964,8f4d1692-0112-407d-95ce-a52bf3aaffd1,/dk/atira/pure/ref2014/researchoutputref2014/o...,REF2014 REF2 output types,"{2966: '/a', 2968: '/b', 2970: '/c', 2972: '/d..."
114,3923,82d8b6b9-812d-4871-afcb-9559282ab6e9,/dk/atira/pure/researchoutput/peerreviewable,Peer review for publication type,"{3925: '/peerreviewable', 3927: '/notpeerrevie..."
115,3935,f1ce2bfe-779c-48b6-8e0e-6f079056cdb3,/dk/atira/pure/researchoutput/category,Publication category,"{3937: '/research', 3941: '/popular', 3943: '/..."
183,12689,d3bd2368-fdf2-4aed-a3f7-38577ba90553,/dk/atira/pure/researchoutput/electronicversio...,Types of publication electronic versions,"{12691: '/preprint', 12693: '/authorsversion',..."
222,15868,9c6436da-0150-4f27-8b2d-04f89342d9fc,/dk/atira/pure/researchoutput/pubmedpublicatio...,PubMed: MeSH publication types,[]
230,16848,d283cfdf-c8be-472b-a3f6-d6f87ef81073,/dk/atira/pure/researchoutput/nontextual/media...,Media of output types for non-textual research...,"{16850: '/online', 16852: '/cd', 16854: '/dvd'..."
231,16860,263d2ca2-0222-421c-8557-bb440c727b0f,/dk/atira/pure/researchoutput/roles/patent,Research output roles (Patent),{16862: '/inventor'}
232,16866,34ffc25c-0cf0-496b-a37c-24a500eef29f,/dk/atira/pure/researchoutput/roles/othercontr...,Research output roles (Other contribution),"{16868: '/author', 16872: '/editor', 8254424: ..."
233,16880,3041e169-6776-4394-afc6-d0869d0353cf,/dk/atira/pure/researchoutput/roles/contributi...,Research output roles (Contribution to journal),"{16882: '/author', 16886: '/editor', 8254404: ..."
234,16896,5c22741b-7de6-4c40-ad8e-97f38f4df51c,/dk/atira/pure/researchoutput/roles/contributi...,Research output roles (Contribution to book/re...,"{16898: '/author', 16902: '/editor', 8254428: ..."
235,16910,1a04f129-b468-40a5-9bcd-04f0fe09f55d,/dk/atira/pure/researchoutput/roles/bookanthology,Research output roles (Book/report),"{16912: '/author', 16916: '/editor', 8254408: ..."
236,16924,c1b67a5f-655a-46fc-9bca-8509ecef9c53,/dk/atira/pure/researchoutput/roles/contributi...,Research output roles (Contribution to confere...,"{16926: '/author', 16928: '/editor', 8254412: ..."
237,16932,6fc23a6f-5cee-4807-abd8-dee3315f9406,/dk/atira/pure/researchoutput/roles/workingpaper,Research output roles (Working paper),{16934: '/author'}
238,16938,46405f72-2763-4833-8c28-877214b661d8,/dk/atira/pure/researchoutput/roles/nontextual,Research output roles (Non textual),"{16940: '/photographer', 16942: '/developer', ..."
239,16972,a384e533-4337-4169-bfcf-e9c47f70d5df,/dk/atira/pure/researchoutput/roles/contributi...,Research output roles (Contribution to special...,"{16974: '/author', 16976: '/editor', 8254418: ..."
240,16980,2f4d1f5b-bc0e-4a89-bc25-21182fed979e,/dk/atira/pure/researchoutput/roles/memorandum,Roles for Memorandum publication authors,"{16982: '/author', 16984: '/illustrator', 1698..."
241,16994,d93982c8-dca6-4c2b-bf9c-93373c196b82,/dk/atira/pure/researchoutput/roles/contributi...,Roles for Contribution to Memorandum publicati...,"{16996: '/author', 16998: '/illustrator', 1700..."
242,17008,379f4ab6-c477-4b42-891a-fcc3053867a4,/dk/atira/pure/researchoutput/roles/thesis,Research output roles (Thesis),"{17010: '/author', 89088535: '/supervisor'}"
243,17014,fe801d94-d2c2-4d18-a4df-676592fe9196,/dk/atira/pure/researchoutput/roles/internalex...,Supervisor roles,"{17016: '/supervisor', 17018: '/advisor'}"
250,4203199,9516e08a-610c-4703-aee4-516d2f9ae64d,/dk/atira/pure/funding/russian_research_specia...,Russian research speciality classifier,"{4204668: '/01', 4204674: '/01/01', 4204684: '..."
254,7730406,aafd7ec2-ff02-4a8a-a4c2-c27972afb256,/dk/atira/pure/keywords/researchexpertizefields,Research expertize fields in SPbU,"{7730414: '/soci', 7730416: '/econ', 7730418: ..."
255,8525794,cc658b07-9b1a-492d-a73a-61bf76106744,/dk/atira/pure/keywords/researchpriorities2016,Priority Areas of Russian Research and Technol...,"{8525802: '/priority1', 8525804: '/priority2',..."
261,19216251,a593a300-64fe-4248-b131-923758ac0f00,/dk/atira/pure/researchoutput/descriptions/boo...,Research output notes (Book/report),[]
262,19216255,494c78c5-d51d-484e-ba8b-40d17142d60a,/dk/atira/pure/researchoutput/descriptions/con...,Research output notes (Contribution to book/re...,[]
263,19216259,eac83561-abb9-43c0-8ebc-c3ede3bc51f5,/dk/atira/pure/researchoutput/descriptions/con...,Research output notes (Contribution to confere...,[]
264,19216263,8b43273f-2d6a-455a-a747-e2c2e893c1dc,/dk/atira/pure/researchoutput/descriptions/con...,Research output notes (Contribution to journal),[]
265,19216267,66657b42-d417-4b5c-af79-546f6b0fb14b,/dk/atira/pure/researchoutput/descriptions/con...,Research output notes (Contribution to Memoran...,[]
266,19216271,84af9936-b1a2-4be7-9f1b-ca6e19a276d1,/dk/atira/pure/researchoutput/descriptions/con...,Research output notes (Contribution to special...,[]
267,19216275,085f2276-569f-4686-aa76-607ff5a21b64,/dk/atira/pure/researchoutput/descriptions/mem...,Research output notes (Memorandum publication ...,[]
268,19216279,8d314682-9b29-4912-8d72-ebc931315b93,/dk/atira/pure/researchoutput/descriptions/non...,Research output notes (Non textual),[]
269,19216283,9f8af4e2-c711-4d34-b632-1803013bdb01,/dk/atira/pure/researchoutput/descriptions/oth...,Research output notes (Other contribution),[]
270,19216287,1eb83f5a-aa8f-4cd5-8c3a-e4c463e5d260,/dk/atira/pure/researchoutput/descriptions/patent,Research output notes (Patent),[]
271,19216291,8c026165-823b-4d9a-b83e-d3feb64c2528,/dk/atira/pure/researchoutput/descriptions/thesis,Research output notes (Thesis),[]
272,19216295,f2cf3f97-9bb0-4d50-9af5-cbe8acdf2ceb,/dk/atira/pure/researchoutput/descriptions/wor...,Research output notes (Working paper),[]
306,93055940,64a1cf5a-caf9-48b1-9c67-8a788f4e4cb9,/dk/atira/pure/keywords/basic_research_programs,Russian Basic Research Programs,"{93055961: '/basic2021', 93055969: '/basic2021..."
307,93580270,0171acaa-f403-4f74-a5f3-b653b8a84d75,/dk/atira/pure/keywords/basic_research_fields,Basic research: prioritized fields 2022,"{93594912: '/01', 93594920: '/01/01', 93594930..."
308,93598328,01d6cb1c-fc71-4dc2-996d-1bbf184fe457,/dk/atira/pure/keywords/basic_research_results,Basic research: expected results 2022,"{93598363: '/01', 93598371: '/01/01', 93598381..."
310,111550260,cb52c10a-e0a9-4422-99b8-a8f0f4e44887,/dk/atira/pure/keywords/russian_research_degre...,Russian research degree classifier 2021,"{111550556: '/01', 111550564: '/01/01', 111550..."

## Результаты

Интересными группами могут быть `/dk/atira/pure/researchoutput/researchoutputtypes` и `/dk/atira/pure/links/researchoutput`. При определении связей с людьми, полезным может быть `/dk/atira/pure/researchoutput/role/*`.

Посмотрим на записи с категориями и типами научной деятельности.

In [12]:
def print_contained_classifications_info(dataframe, uri):
    row = dataframe[dataframe['uri'] == uri].index[0]
    dict_entries = dataframe.loc[row, 'contained_classifications_ids']

    print(f"Total elements: {len(dict_entries)}")
    for key, value in dict_entries.items():
        print(f"{key}: {value}")

По всей видимости, `category` - более общая группа для научной деятельности.

In [13]:
print_contained_classifications_info(
    dataframe=parsed_classification_df,
    uri='/dk/atira/pure/researchoutput/category',
)

Total elements: 6
3937: /research
3941: /popular
3943: /other
3939: /education
19236878: /transfer
19236880: /communication

`type` более точно определяет тип деятельности:

In [14]:
print_contained_classifications_info(
    dataframe=parsed_classification_df, 
    uri='/dk/atira/pure/researchoutput/researchoutputtypes'
)

Total elements: 77
2827: /contributiontobookanthology
3949: /contributiontojournal
3959: /bookanthology
3953: /contributiontoperiodical
3961: /workingpaper
3951: /contributiontoconference
3963: /nontextual
3965: /thesis
3955: /patent
3967: /memorandum
3969: /contributiontomemorandum
3957: /othercontribution
3973: /contributiontojournal/article
3977: /contributiontojournal/letter
3981: /contributiontojournal/comment
3985: /contributiontojournal/book
3989: /contributiontojournal/scientific
3993: /contributiontojournal/systematicreview
3997: /contributiontojournal/shortsurvey
4001: /contributiontojournal/editorial
4005: /contributiontojournal/abstract
4011: /contributiontobookanthology/article
4015: /contributiontobookanthology/chapter
4022: /contributiontobookanthology/entry
4029: /contributiontobookanthology/conference
4036: /contributiontobookanthology/foreword
4043: /contributiontobookanthology/other
4052: /contributiontoconference/paper
4056: /contributiontoconference/poster
4060: /contributiontoconference/abstract
4064: /contributiontoconference/other
4070: /contributiontoperiodical/article
4076: /contributiontoperiodical/featured
4082: /contributiontoperiodical/book
4086: /contributiontoperiodical/editorial
4092: /contributiontoperiodical/letter
4098: /contributiontoperiodical/special
4107: /patent/patent
4113: /othercontribution/other
4122: /bookanthology/book
4129: /bookanthology/anthology
4136: /bookanthology/encyclopedia
4143: /bookanthology/preprint
4147: /bookanthology/scholarly
4151: /bookanthology/commissioned
4155: /bookanthology/manual
4159: /bookanthology/materials
4163: /bookanthology/authorsabstract
4167: /bookanthology/other
4173: /workingpaper/workingpaper
4177: /workingpaper/discussionpaper
4183: /nontextual/software
4187: /nontextual/database
4191: /nontextual/digitalorvisualproducts
4195: /nontextual/web
4202: /nontextual/artefact
4206: /nontextual/exhibition
4210: /nontextual/performance
4214: /nontextual/composition
4218: /nontextual/design
4224: /thesis/hab
4228: /thesis/doc
4232: /thesis/master
4238: /memorandum/academicmemorandum
4242: /memorandum/qahearing
4248: /contributiontomemorandum/contributiontoacademicmemorandum
4252: /contributiontomemorandum/contributiontoqahearing
19216595: /contributiontojournal/conferencearticle
48701515: /patent/patent_application
48703514: /patent/cerficate_of_registration
76632383: /contributiontobookanthology/abstracts
78864637: /workingpaper/preprint
129627977: /contributiontojournal/biographical_item
129627980: /contributiontojournal/information_item
129654679: /bookanthology/catalogue
131071411: /contributiontojournal/statement_in_the_discussion
135119523: /bookanthology/conference_proceedings

Посмотрим на запись со ссылками:

In [15]:
print_contained_classifications_info(
    dataframe=parsed_classification_df,
    uri='/dk/atira/pure/links/researchoutput'
)

Total elements: 4
921: /unspecified
12683: /scopuspublication
12685: /scopuscitations
64558712: /portalmultimedia