# Связь Research Output с Person и Organisational Unit

`WSResearchOutput` содержит `personAssociations`, который - массив `WSClassifiedAuthorAssociation`.
То есть у одного ресерча может быть несколько авторов.

Посмотрим на структуру `WSClassifiedAuthorAssociation`.

## Импорт зависимостей

In [9]:
# imports
import os
import json
import pandas as pd

In [10]:
from notebooks import utils

## Чтение спецификации

In [11]:
SWAGGER_SPEC_PATH = 'notebooks/522-swagger-pretty.json'
api_spec = utils.load_from_json(SWAGGER_SPEC_PATH)

In [12]:
classified_author_schema = utils.fetch_schema(api_spec, 'WSClassifiedAuthorAssociation')
classified_author_schema

                      field                               type
6       authorCollaboration           WSAuthorCollaborationRef
11  contributionDescription                 Primitive <string>
12   contributionPercentage                 Primitive <double>
14      correspondingAuthor                Primitive <boolean>
13                  country                   WSClassification
1                externalId                 Primitive <string>
2          externalIdSource                 Primitive <string>
10    externalOrganisations  Array <WSExternalOrganisationRef>
5            externalPerson                WSExternalPersonRef
3         externallyManaged                Primitive <boolean>
15                   hidden                Primitive <boolean>
7                      name                             WSName
9       organisationalUnits          Array <WSOrganisationRef>
4                    person                        WSPersonRef
8                personRole                   WSClassification
0                    pureId                  Primitive <int64>

С `Person` оно связывается через `WSPersonRef`.
Посмотрим и на него:

In [13]:
classified_author_schema = utils.fetch_schema(api_spec, 'WSPersonRef')
classified_author_schema

               field                 type
4         externalId   Primitive <string>
5   externalIdSource   Primitive <string>
6  externallyManaged  Primitive <boolean>
1               link     WSNavigationLink
2               name    WSLocalizedString
7                ref             WSPerson
3               type     WSClassification
0               uuid   Primitive <string>

Важным является `uuid`, который связывает запись с идентификатором человека из `persons.json`.
Или которого можно найти в системе по этому `uuid`.

Аналогичную структуру имеют и организации:

In [14]:
organisation_ref_schema = utils.fetch_schema(api_spec, 'WSOrganisationRef')
organisation_ref_schema

               field                 type
4         externalId   Primitive <string>
5   externalIdSource   Primitive <string>
6  externallyManaged  Primitive <boolean>
1               link     WSNavigationLink
2               name    WSLocalizedString
7                ref       WSOrganisation
3               type     WSClassification
0               uuid   Primitive <string>

На первый взгляд, `WS***Ref` типы создают "связки" между объектами, у которых можно использовать `uuid` сущности-таргета.